[package]
name = "concread"
version = "0.1.20"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"

description = "Concurrently Readable Data-Structures for Rust"
documentation = "https://docs.rs/concread/latest/concread/"
homepage = "https://github.com/kanidm/concread/"
repostiory = "https://github.com/kanidm/concread/"
readme = "README.md"
keywords = ["data-structures", "concread", "concurrency", "parallel",]
categories = ["data-structures", "memory-management",]
license = "MPL-2.0"

[features]
simd_support = ["packed_simd"]
asynch = ["tokio"]
skinny = []

[dependencies]
crossbeam-epoch = "0.8"
crossbeam-utils = "0.7"
crossbeam = "0.7"
parking_lot = "0.10"
num = "0.2.0"
smallvec = "1.4"
ahash = "0.3"
rand = "0.7"
packed_simd = { version = "0.3", optional = true }
tokio = { version = "0.2", optional = true, features = ["sync"] }

[dev-dependencies]
time = "0.2"
async-std = "1.6"

[[bin]]
name = "unsound"
path = "src/unsound.rs"

