[package]
name = "concread"
version = "0.2.8"
authors = ["William Brown <william@blackhats.net.au>"]

description = "Concurrently Readable Data-Structures for Rust"
documentation = "https://docs.rs/concread/latest/concread/"
homepage = "https://github.com/kanidm/concread/"
repostiory = "https://github.com/kanidm/concread/"
readme = "README.md"
keywords = ["data-structures", "concread", "concurrency", "parallel",]
categories = ["data-structures", "memory-management", "caching", "lru", "arc"]
license = "MPL-2.0"

[features]
simd_support = ["packed_simd"]
skinny = []
unsoundness = []

[dependencies]
crossbeam-epoch = "0.9"
crossbeam-utils = "0.8"
crossbeam = "0.8"
parking_lot = "0.11"
smallvec = "1.4"
ahash = "0.7"
rand = "0.8"
packed_simd = { version = "0.3", optional = true, package = "packed_simd_2" }

[dev-dependencies]
time = "0.2"
criterion = "0.3"

[[bin]]
name = "unsound"
path = "src/unsound.rs"

[[bin]]
name = "unsound2"
path = "src/unsound2.rs"

[[bin]]
name = "unsound3"
path = "src/unsound3.rs"

[[bench]]
name = "hashmap_benchmark"
harness = false
